### PR TITLE
improve sm2 performance

### PR DESCRIPTION
**Pull request by warm3snow**
```
BenchmarkSM2SignParallel-4     	    2000	    905135 ns/op	 1161902 B/op	   11346 allocs/op
BenchmarkECDSASignParallel-4   	  100000	     14311 ns/op	    4729 B/op	      70 allocs/op
BenchmarkFastSM2Parallel-4     	    5000	    306753 ns/op	  317280 B/op	    3259 allocs/op
PASS
ok  	github.com/warm3snow/xxx/performace	5.075s
```
Speed up to 3x.   
BenchmarkFastSM2Parallel show the performance of improved SM2.

### CODE REVIEW

**Comment by warm3snow** [comment]
Use Jacobian Coordinates and Sliding Windows to optimize SM2 ScalarBaseMult operation.

**Comment by tjfoc** [comment]
good. we are working on the performance improve too. Will review and merge this when we done. 
thanks.

**Comment by xtaci** [comment]
nice, try to optimize every critical path, *cache coherently*!

**Comment by warm3snow** [comment]
I made a stupid mistake. I copy a wrong preComputed table.  Will fix it sooner~ . :-(

**Comment by tjfoc** [comment]
we will push one improved version by this week.

**Comment by tjfoc** [comment]
just updated one performance improvement version in develop branch.

**Comment by tjfoc** [comment]
close for now

**Pull request closed without merging**
